server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/payment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true